### ISSUE TITLE
[Autoware-10] Error recovering cv_tracker/obj_reproj

### ISSUE THREAD

**Issue by tobiasduerschmid** [rosqual/rosdiscover#184]
When trying to recover cv_tracker/obj_reproj in both the buggy and fixed version of autoware-10, we get this error: `obj_reproj is not in the CMakeLists.txt of package 'cv_tracker`. However, there is an entry in https://github.com/Autoware-AI/autoware.ai/blob/0583e6d128450b2c567732cb9a00b828af7cd93e/ros/src/computing/perception/detection/packages/cv_tracker/CMakeLists.txt: 
```
ADD_EXECUTABLE(obj_reproj
  nodes/obj_reproj/obj_reproj.cpp
)
```
[buggy.system-recovery.log](https://github.com/rosqual/rosdiscover/files/7171768/buggy.system-recovery.log)

**Comment by schmerl** [comment]
This bug should now be fixed. The problem was that the CMakeLists.txt processing was not considering commands to be case insensitive.

**Comment by tobiasduerschmid** [comment]
Yes. It's fixed
